### ISSUE TITLE
Crashing on Launch

### ISSUE THREAD

**Issue by Tropenfisch69** [petrolpark/Destroy#224]
Mod: Create - Destroy
Version: 1.20.1 & Every Destroy version
Forge-Version: 47.2.0
Issue: Crashing on launch

I tried downgrading optifine, without optifine, with new forge version, but it didnt help

Crash Report:
[crash-2024-01-27_12.36.31-client.txt](https://github.com/petrolpark/Destroy/files/14072107/crash-2024-01-27_12.36.31-client.txt)

or:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-01-27 12:36:31
Description: Initializing game

java.lang.ExceptionInInitializerError: null
	at net.minecraft.client.gui.Gui.<clinit>(Gui.java:81) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:destroy.mixins.json:GuiMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGui,pl:mixin:APP:webdisplays.mixins.json:OverlayMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:521) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1-forge-47.2.20.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.getModEventBus()" because the return value of "net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.get()" is null
	at com.tterrag.registrate.AbstractRegistrate.getModEventBus(AbstractRegistrate.java:222) ~[Registrate-MC1.20-1.3.3.jar%23278!/:?] {re:classloading}
	at com.tterrag.registrate.util.OneTimeEventReceiver.addModListener(OneTimeEventReceiver.java:42) ~[Registrate-MC1.20-1.3.3.jar%23278!/:?] {re:classloading}
	at com.tterrag.registrate.util.OneTimeEventReceiver.addModListener(OneTimeEventReceiver.java:34) ~[Registrate-MC1.20-1.3.3.jar%23278!/:?] {re:classloading}
	at com.tterrag.registrate.util.OneTimeEventReceiver.addModListener(OneTimeEventReceiver.java:40) ~[Registrate-MC1.20-1.3.3.jar%23278!/:?] {re:classloading}
	at com.tterrag.registrate.util.OneTimeEventReceiver.addModListener(OneTimeEventReceiver.java:34) ~[Registrate-MC1.20-1.3.3.jar%23278!/:?] {re:classloading}
	at com.tterrag.registrate.AbstractRegistrate.makeRegistry(AbstractRegistrate.java:910) ~[Registrate-MC1.20-1.3.3.jar%23278!/:?] {re:classloading}
	at com.petrolpark.destroy.Destroy.<clinit>(Destroy.java:97) ~[destroy-1.20.1-0.6.jar%23228!/:0.6] {re:mixin,re:classloading}
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at net.minecraft.client.gui.Gui.<clinit>(Gui.java:81) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:destroy.mixins.json:GuiMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGui,pl:mixin:APP:webdisplays.mixins.json:OverlayMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:521) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Erweiterte Windows 32 Base-API:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Bibliothek für Steuerelemente:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Krypto-API32:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		ColorAdapterClient.dll:Microsoft Color Adapter Client:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.19041.3930:Microsoft Corporation
		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.19041.3636:Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.19041.3996 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS-Client-API-DLL:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.3996 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL-Hilfsprogrammbibliotheks-DLL:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.3996 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP-Hilfs-API:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Client-DLL für Windows NT-Basis-API:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Client-DLL für Windows NT-Basis-API:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:MMDevice-API:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF-Server-DLL:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.23110.3 (9ebb3643d539a6fc4659898b1df3124d5da4c0a9):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		OpenAL.dll:Main implementation library:1.21.1:
		POWRPROF.dll:Power Profile Helper DLL:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		PROPSYS.dll:Microsoft-Eigenschaftensystem:7.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remoteprozeduraufruf-Laufzeitumgebung:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		SETUPAPI.dll:Windows Setup-API:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Allgemeine Windows-Shell-DLL:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll
		USER32.dll:Client-DLL für Windows USER-API (mehrere Benutzer):10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP-Dienste:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API-DLL:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		WINSTA.dll:Winstation Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0-32-Bit-DLL:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows-Sperrungsrichtlinie:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Bibliothek mit kryptografischen Primitiven von Windows:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.19041.3996 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM für Windows:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		cryptbase.dll:Base cryptographic API DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		cryptnet.dll:Crypto Network Related API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Clientdienst:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6-Client:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		drvstore.dll:Driver Store API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		dwmapi.dll:Microsoft Desktopfenster-Manager-API:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.19041.3996 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec Benutzermodus-API:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.3996 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		gpapi.dll:Gruppenrichtlinienclient-API:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		icm32.dll:Microsoft Color Management Module (CMM):10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		imagehlp.dll:Windows NT Image Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		inputhost.dll:InputHost:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jna11479590969813711321.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.19041.3758 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		msasn1.dll:ASN.1 Runtime APIs:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		mscms.dll:Microsoft-Farbabstimmungssystem-DLL:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0-Dienstanbieter:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-Mail-Namenshimanbieter:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt-Router:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		ntdll.dll:DLL für NT-Layer:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA-Anbieter:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		nvgpucomp64.dll:NVIDIA GPU Compiler Driver, Version 546.33 :31.0.15.4633:NVIDIA Corporation
		nvoglv64.dll:NVIDIA Compatible OpenGL ICD:31.0.15.4633:NVIDIA Corporation
		nvspcap64.dll:NVIDIA Game Proxy:3.27.0.120:NVIDIA Corporation
		ole32.dll:Microsoft OLE für Windows:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		opengl32.dll:OpenGL Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		pdh.dll:Windows Unterstützungs-DLL für Leistungsdaten:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:DLL für Windows-Systemleistungsobjekte:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		perfproc.dll:DLL für Windows-Verarbeitungsleistungsobjekte:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP-Namespaceanbieter:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight-Hilfsprogrammbibliothek:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.19041.3996 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Microsoft UxTheme-Bibliothek:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		win32u.dll:Win32u:10.0.19041.3996 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage-API:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		wintrust.dll:Microsoft Trust Verification APIs:10.0.19041.3996 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows-Basistypen-DLL:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		xinput1_4.dll:API für Microsoft Common Controller:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1-forge-47.2.20.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 272268216 bytes (259 MiB) / 704643072 bytes (672 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4633
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 23471.82
	Virtual memory used (MB): 18225.63
	Swap memory total (MB): 7168.00
	Swap memory used (MB): 674.07
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.20.1-forge-47.2.20
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.33, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.20.1-47.2.20-universal.jar                |Forge                         |forge                         |47.2.20             |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90

**Comment by petrolpark** [comment]
Because nobody has complained incessantly about a crash like this, I'm assuming this doesn't happen anymore.
